//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.News {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtAddDateTime;
		protected global::System.Web.UI.WebControls.TextBox txtAuthor;
		protected global::System.Web.UI.WebControls.TextBox txtContent;
		protected global::System.Web.UI.WebControls.TextBox txtDescription;
		protected global::System.Web.UI.WebControls.TextBox txtFileURL;
		protected global::System.Web.UI.WebControls.TextBox txtFromWhere;
	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtInfo;
		protected global::System.Web.UI.WebControls.CheckBox chkIsDelete;
		protected global::System.Web.UI.WebControls.CheckBox chkIsLock;
		protected global::System.Web.UI.WebControls.CheckBox chkIsTJ;
		protected global::System.Web.UI.WebControls.CheckBox chkIsHot;
		protected global::System.Web.UI.WebControls.CheckBox chkIsTop;
		protected global::System.Web.UI.WebControls.TextBox txtKeyWord;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL;
		protected global::System.Web.UI.WebControls.TextBox txtReadCount;
		protected global::System.Web.UI.WebControls.TextBox txtSortID;
		protected global::System.Web.UI.WebControls.TextBox txtTag;
		protected global::System.Web.UI.WebControls.TextBox txtTitle;
		protected global::System.Web.UI.WebControls.TextBox txtURL;
		protected global::System.Web.UI.WebControls.TextBox txtVideoURL;
		protected global::System.Web.UI.WebControls.TextBox txtWeight;
		protected global::System.Web.UI.WebControls.TextBox txtSiteID;
		protected global::System.Web.UI.WebControls.TextBox txtUninoID;
		protected global::System.Web.UI.WebControls.TextBox txtUserID;
		protected global::System.Web.UI.WebControls.CheckBox chkIsPic;
		protected global::System.Web.UI.WebControls.CheckBox chkIsStore;
		protected global::System.Web.UI.WebControls.TextBox txtDingNum;
		protected global::System.Web.UI.WebControls.TextBox txtZhuangNum;
		protected global::System.Web.UI.WebControls.TextBox txtZhiChiNum;
		protected global::System.Web.UI.WebControls.TextBox txtSCNum;
		protected global::System.Web.UI.WebControls.CheckBox chkHasAddress;
		protected global::System.Web.UI.WebControls.TextBox txtAddressName;
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtAddressX;
		protected global::System.Web.UI.WebControls.TextBox txtAddressY;
		protected global::System.Web.UI.WebControls.TextBox txtShopMenberID;
		protected global::System.Web.UI.WebControls.TextBox txtShareTxt;
		protected global::System.Web.UI.WebControls.TextBox txtSharePicID;
		protected global::System.Web.UI.WebControls.TextBox txtShareMainPicUrl;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
