//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.News {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblAddDateTime;
	protected global::System.Web.UI.WebControls.Label lblAuthor;
	protected global::System.Web.UI.WebControls.Label lblContent;
	protected global::System.Web.UI.WebControls.Label lblDescription;
	protected global::System.Web.UI.WebControls.Label lblFileURL;
	protected global::System.Web.UI.WebControls.Label lblFromWhere;
	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblInfo;
	protected global::System.Web.UI.WebControls.Label lblIsDelete;
	protected global::System.Web.UI.WebControls.Label lblIsLock;
	protected global::System.Web.UI.WebControls.Label lblIsTJ;
	protected global::System.Web.UI.WebControls.Label lblIsHot;
	protected global::System.Web.UI.WebControls.Label lblIsTop;
	protected global::System.Web.UI.WebControls.Label lblKeyWord;
	protected global::System.Web.UI.WebControls.Label lblPicURL;
	protected global::System.Web.UI.WebControls.Label lblReadCount;
	protected global::System.Web.UI.WebControls.Label lblSortID;
	protected global::System.Web.UI.WebControls.Label lblTag;
	protected global::System.Web.UI.WebControls.Label lblTitle;
	protected global::System.Web.UI.WebControls.Label lblURL;
	protected global::System.Web.UI.WebControls.Label lblVideoURL;
	protected global::System.Web.UI.WebControls.Label lblWeight;
	protected global::System.Web.UI.WebControls.Label lblSiteID;
	protected global::System.Web.UI.WebControls.Label lblUninoID;
	protected global::System.Web.UI.WebControls.Label lblUserID;
	protected global::System.Web.UI.WebControls.Label lblIsPic;
	protected global::System.Web.UI.WebControls.Label lblIsStore;
	protected global::System.Web.UI.WebControls.Label lblDingNum;
	protected global::System.Web.UI.WebControls.Label lblZhuangNum;
	protected global::System.Web.UI.WebControls.Label lblZhiChiNum;
	protected global::System.Web.UI.WebControls.Label lblSCNum;
	protected global::System.Web.UI.WebControls.Label lblHasAddress;
	protected global::System.Web.UI.WebControls.Label lblAddressName;
	protected global::System.Web.UI.WebControls.Label lblAddress;
	protected global::System.Web.UI.WebControls.Label lblAddressX;
	protected global::System.Web.UI.WebControls.Label lblAddressY;
	protected global::System.Web.UI.WebControls.Label lblShopMenberID;
	protected global::System.Web.UI.WebControls.Label lblShareTxt;
	protected global::System.Web.UI.WebControls.Label lblSharePicID;
	protected global::System.Web.UI.WebControls.Label lblShareMainPicUrl;


       
    }
}
