//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Message {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtMName;
		protected global::System.Web.UI.WebControls.TextBox txtMPhone;
		protected global::System.Web.UI.WebControls.TextBox txtMEmail;
		protected global::System.Web.UI.WebControls.TextBox txtMAdress;
		protected global::System.Web.UI.WebControls.TextBox txtMContent;
		protected global::System.Web.UI.WebControls.TextBox txtMDate;
		protected global::System.Web.UI.WebControls.CheckBox chkMState;
		protected global::System.Web.UI.WebControls.TextBox txtavg1;
		protected global::System.Web.UI.WebControls.TextBox txtavg2;
		protected global::System.Web.UI.WebControls.TextBox txtavg3;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
