//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Product {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtPicURL;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL1;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL2;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL3;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL4;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL5;
		protected global::System.Web.UI.WebControls.TextBox txtTitle;
		protected global::System.Web.UI.WebControls.TextBox txtDescription;
		protected global::System.Web.UI.WebControls.TextBox txtTag;
		protected global::System.Web.UI.WebControls.TextBox txtInfo;
		protected global::System.Web.UI.WebControls.CheckBox chkIsHot;
		protected global::System.Web.UI.WebControls.CheckBox chkIsTop;
		protected global::System.Web.UI.WebControls.CheckBox chkIsTJ;
		protected global::System.Web.UI.WebControls.TextBox txtKeyWord;
		protected global::System.Web.UI.WebControls.TextBox txtSortID;
		protected global::System.Web.UI.WebControls.TextBox txtVideoURL;
		protected global::System.Web.UI.WebControls.TextBox txtWeight;
		protected global::System.Web.UI.WebControls.TextBox txtReadCount;
		protected global::System.Web.UI.WebControls.CheckBox chkIsLock;
		protected global::System.Web.UI.WebControls.CheckBox chkIsDelete;
		protected global::System.Web.UI.WebControls.TextBox txtTitle2;
		protected global::System.Web.UI.WebControls.TextBox txtavg1;
		protected global::System.Web.UI.WebControls.TextBox txtavg2;
		protected global::System.Web.UI.WebControls.CheckBox chkavg3;
		protected global::System.Web.UI.WebControls.TextBox txtAddDateTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
