//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Product {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblPicURL;
	protected global::System.Web.UI.WebControls.Label lblPicURL1;
	protected global::System.Web.UI.WebControls.Label lblPicURL2;
	protected global::System.Web.UI.WebControls.Label lblPicURL3;
	protected global::System.Web.UI.WebControls.Label lblPicURL4;
	protected global::System.Web.UI.WebControls.Label lblPicURL5;
	protected global::System.Web.UI.WebControls.Label lblTitle;
	protected global::System.Web.UI.WebControls.Label lblDescription;
	protected global::System.Web.UI.WebControls.Label lblTag;
	protected global::System.Web.UI.WebControls.Label lblInfo;
	protected global::System.Web.UI.WebControls.Label lblIsHot;
	protected global::System.Web.UI.WebControls.Label lblIsTop;
	protected global::System.Web.UI.WebControls.Label lblIsTJ;
	protected global::System.Web.UI.WebControls.Label lblKeyWord;
	protected global::System.Web.UI.WebControls.Label lblSortID;
	protected global::System.Web.UI.WebControls.Label lblVideoURL;
	protected global::System.Web.UI.WebControls.Label lblWeight;
	protected global::System.Web.UI.WebControls.Label lblReadCount;
	protected global::System.Web.UI.WebControls.Label lblIsLock;
	protected global::System.Web.UI.WebControls.Label lblIsDelete;
	protected global::System.Web.UI.WebControls.Label lblTitle2;
	protected global::System.Web.UI.WebControls.Label lblavg1;
	protected global::System.Web.UI.WebControls.Label lblavg2;
	protected global::System.Web.UI.WebControls.Label lblavg3;
	protected global::System.Web.UI.WebControls.Label lblAddDateTime;


       
    }
}
