//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.About {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtDescription;
		protected global::System.Web.UI.WebControls.TextBox txtInfo;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL;
		protected global::System.Web.UI.WebControls.TextBox txtavg1;
		protected global::System.Web.UI.WebControls.CheckBox chkavg2;
		protected global::System.Web.UI.WebControls.TextBox txtavg3;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL1;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL2;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL3;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL4;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL5;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL6;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL7;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL8;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL9;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL10;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL11;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL12;
		protected global::System.Web.UI.WebControls.TextBox txtPicURL13;
		protected global::System.Web.UI.WebControls.TextBox txtWAdress;
		protected global::System.Web.UI.WebControls.TextBox txtAdress;
		protected global::System.Web.UI.WebControls.TextBox txtPhone;
		protected global::System.Web.UI.WebControls.TextBox txtCPhone;
		protected global::System.Web.UI.WebControls.TextBox txtPostNum;
		protected global::System.Web.UI.WebControls.TextBox txtAPicURL;
		protected global::System.Web.UI.WebControls.TextBox txtavg4;
		protected global::System.Web.UI.WebControls.TextBox txtavg5;
		protected global::System.Web.UI.WebControls.CheckBox chkavg6;
		protected global::System.Web.UI.WebControls.TextBox txtJDtxt1;
		protected global::System.Web.UI.WebControls.TextBox txtJDtxt2;
		protected global::System.Web.UI.WebControls.TextBox txtJDtxt3;
		protected global::System.Web.UI.WebControls.TextBox txtJDtxt4;
		protected global::System.Web.UI.WebControls.TextBox txtJDtxt5;
		protected global::System.Web.UI.WebControls.TextBox txtWXURL1;
		protected global::System.Web.UI.WebControls.TextBox txtWXURL2;
		protected global::System.Web.UI.WebControls.TextBox txtWXURL3;
		protected global::System.Web.UI.WebControls.TextBox txtJDtxt6;
		protected global::System.Web.UI.WebControls.TextBox txtJDtxt7;
		protected global::System.Web.UI.WebControls.TextBox txtJDtxt8;
		protected global::System.Web.UI.WebControls.TextBox txtJDtxt9;
		protected global::System.Web.UI.WebControls.TextBox txtJDtxt10;
		protected global::System.Web.UI.WebControls.TextBox txtTitle1;
		protected global::System.Web.UI.WebControls.TextBox txtTitle2;
		protected global::System.Web.UI.WebControls.TextBox txtTitle3;
		protected global::System.Web.UI.WebControls.TextBox txtTitle4;
		protected global::System.Web.UI.WebControls.TextBox txtTitle5;
		protected global::System.Web.UI.WebControls.TextBox txtTitle7;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
