//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.About {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblDescription;
	protected global::System.Web.UI.WebControls.Label lblInfo;
	protected global::System.Web.UI.WebControls.Label lblPicURL;
	protected global::System.Web.UI.WebControls.Label lblavg1;
	protected global::System.Web.UI.WebControls.Label lblavg2;
	protected global::System.Web.UI.WebControls.Label lblavg3;
	protected global::System.Web.UI.WebControls.Label lblPicURL1;
	protected global::System.Web.UI.WebControls.Label lblPicURL2;
	protected global::System.Web.UI.WebControls.Label lblPicURL3;
	protected global::System.Web.UI.WebControls.Label lblPicURL4;
	protected global::System.Web.UI.WebControls.Label lblPicURL5;
	protected global::System.Web.UI.WebControls.Label lblPicURL6;
	protected global::System.Web.UI.WebControls.Label lblPicURL7;
	protected global::System.Web.UI.WebControls.Label lblPicURL8;
	protected global::System.Web.UI.WebControls.Label lblPicURL9;
	protected global::System.Web.UI.WebControls.Label lblPicURL10;
	protected global::System.Web.UI.WebControls.Label lblPicURL11;
	protected global::System.Web.UI.WebControls.Label lblPicURL12;
	protected global::System.Web.UI.WebControls.Label lblPicURL13;
	protected global::System.Web.UI.WebControls.Label lblWAdress;
	protected global::System.Web.UI.WebControls.Label lblAdress;
	protected global::System.Web.UI.WebControls.Label lblPhone;
	protected global::System.Web.UI.WebControls.Label lblCPhone;
	protected global::System.Web.UI.WebControls.Label lblPostNum;
	protected global::System.Web.UI.WebControls.Label lblAPicURL;
	protected global::System.Web.UI.WebControls.Label lblavg4;
	protected global::System.Web.UI.WebControls.Label lblavg5;
	protected global::System.Web.UI.WebControls.Label lblavg6;
	protected global::System.Web.UI.WebControls.Label lblJDtxt1;
	protected global::System.Web.UI.WebControls.Label lblJDtxt2;
	protected global::System.Web.UI.WebControls.Label lblJDtxt3;
	protected global::System.Web.UI.WebControls.Label lblJDtxt4;
	protected global::System.Web.UI.WebControls.Label lblJDtxt5;
	protected global::System.Web.UI.WebControls.Label lblWXURL1;
	protected global::System.Web.UI.WebControls.Label lblWXURL2;
	protected global::System.Web.UI.WebControls.Label lblWXURL3;
	protected global::System.Web.UI.WebControls.Label lblJDtxt6;
	protected global::System.Web.UI.WebControls.Label lblJDtxt7;
	protected global::System.Web.UI.WebControls.Label lblJDtxt8;
	protected global::System.Web.UI.WebControls.Label lblJDtxt9;
	protected global::System.Web.UI.WebControls.Label lblJDtxt10;
	protected global::System.Web.UI.WebControls.Label lblTitle1;
	protected global::System.Web.UI.WebControls.Label lblTitle2;
	protected global::System.Web.UI.WebControls.Label lblTitle3;
	protected global::System.Web.UI.WebControls.Label lblTitle4;
	protected global::System.Web.UI.WebControls.Label lblTitle5;
	protected global::System.Web.UI.WebControls.Label lblTitle7;


       
    }
}
