//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.GMile {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtGName;
		protected global::System.Web.UI.WebControls.TextBox txtGContent;
		protected global::System.Web.UI.WebControls.TextBox txtGDate;
		protected global::System.Web.UI.WebControls.TextBox txtGChannel;
		protected global::System.Web.UI.WebControls.CheckBox chkGState;
		protected global::System.Web.UI.WebControls.TextBox txtavg5;
		protected global::System.Web.UI.WebControls.TextBox txtFaceURL;
		protected global::System.Web.UI.WebControls.CheckBox chkIsLock;
		protected global::System.Web.UI.WebControls.TextBox txtPicUrl;
		protected global::System.Web.UI.WebControls.TextBox txtRouteUrl;
		protected global::System.Web.UI.WebControls.TextBox txtMsgType;
		protected global::System.Web.UI.WebControls.TextBox txtMsgSortID;
		protected global::System.Web.UI.WebControls.TextBox txtTargetID;
		protected global::System.Web.UI.WebControls.TextBox txtMsgParentID;
		protected global::System.Web.UI.WebControls.TextBox txtLevel;
		protected global::System.Web.UI.WebControls.TextBox txtIP;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
