//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.GMile {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblGName;
	protected global::System.Web.UI.WebControls.Label lblGContent;
	protected global::System.Web.UI.WebControls.Label lblGDate;
	protected global::System.Web.UI.WebControls.Label lblGChannel;
	protected global::System.Web.UI.WebControls.Label lblGState;
	protected global::System.Web.UI.WebControls.Label lblavg5;
	protected global::System.Web.UI.WebControls.Label lblFaceURL;
	protected global::System.Web.UI.WebControls.Label lblIsLock;
	protected global::System.Web.UI.WebControls.Label lblPicUrl;
	protected global::System.Web.UI.WebControls.Label lblRouteUrl;
	protected global::System.Web.UI.WebControls.Label lblMsgType;
	protected global::System.Web.UI.WebControls.Label lblMsgSortID;
	protected global::System.Web.UI.WebControls.Label lblTargetID;
	protected global::System.Web.UI.WebControls.Label lblMsgParentID;
	protected global::System.Web.UI.WebControls.Label lblLevel;
	protected global::System.Web.UI.WebControls.Label lblIP;


       
    }
}
